### ISSUE TITLE
Timings command line option not working?

### ISSUE THREAD

**Issue by danyill** [Mogztter/asciidoctor-pdf.js#159]
When using the `-t` timings option on `master` or `alpha.4` I receive some errors which I think is to do with the Opal conversion of asciidoctor.js? But that doesn't seem right because using asciidoctor.js command line works fine. So filing here...

```
error { format: undefined method `format' for "%05.5f"
    at String.$$method_missing (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/asciidoctor-opal-runtime/src/opal.js:3907:56)
    at String.method_missing_stub (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/asciidoctor-opal-runtime/src/opal.js:1310:35)
    at String.$String_$percent$5 (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/asciidoctor-opal-runtime/src/opal.js:6437:21)
    at constructor.$$print_report (/home/mulhollandd/Documents/asciidoctor-pdf.js/node_modules/@asciidoctor/core/dist/node/asciidoctor.js:16408:76)
    at Object.convert (/home/mulhollandd/Documents/asciidoctor-pdf.js/lib/converter.js:74:13)
    at convertFiles (/home/mulhollandd/Documents/asciidoctor-pdf.js/lib/cli.js:15:21)
    at PdfInvoker.invoke (/home/mulhollandd/Documents/asciidoctor-pdf.js/lib/cli.js:64:13)
    at /home/mulhollandd/Documents/asciidoctor-pdf.js/bin/asciidoctor-pdf:10:34
    at Object.<anonymous> (/home/mulhollandd/Documents/asciidoctor-pdf.js/bin/asciidoctor-pdf:11:3)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
  name: 'format',
  message: 'undefined method `format\' for "%05.5f"',
```

**Comment by Mogztter** [comment]
Which version of Asciidoctor.js are you using?

**Comment by danyill** [comment]
When I test using asciidoctor.js:

```
/home/mulhollandd/.nvm/versions/node/v10.16.3/bin/asciidoctor -v
Asciidoctor.js 2.0.3 (Asciidoctor 2.0.9) [https://asciidoctor.org]
Runtime Environment (node v10.16.3 on linux)
CLI version 3.2.0
```

**Comment by Mogztter** [comment]
I meant when using `asciidoctor-pdf`, could you please run the same command but with `asciidoctor-pdf`?

**Comment by danyill** [comment]
Ah, sorry -- this one:

```
asciidoctor-pdf -v
Asciidoctor PDF 1.0.0-alpha.4 using Asciidoctor.js 2.0.2 (Asciidoctor 2.0.7) [https://asciidoctor.org]
Runtime Environment (node v10.16.3 on linux)
CLI version 3.0.2
```

**Comment by Mogztter** [comment]
Oh I've actually removed the `format` method in Opal runtime to reduce the runtime size.
We need to use the new Asciidoctor.js API `printReport`:


```js
timer.printReport(process.stderr, inputFile.contents ? '-' : inputFile.path)
```

See: https://github.com/asciidoctor/asciidoctor-cli.js/pull/83/files
