### ISSUE TITLE
Error when building master 

### ISSUE THREAD

**Issue by rohel01** [Mogztter/asciidoctor-pdf.js#162]
Hello,

I am on Ubuntu 19.04. When trying to build from the master branch (c4988fda3904c0e1112d8584b8f8aaa9de52a30c), I get the following messages 

```shell
michael:asciidoctor-pdf.js$ npm install

> ghostscript4js@3.1.1 install /home/michael/src/asciidoctor-pdf.js/node_modules/ghostscript4js
> node-gyp rebuild

make : on entre dans le répertoire « /home/michael/src/asciidoctor-pdf.js/node_modules/ghostscript4js/build »
  CC(target) Release/obj.target/nothing/../node-addon-api/src/nothing.o
  AR(target) Release/obj.target/../node-addon-api/src/nothing.a
  COPY Release/nothing.a
  CXX(target) Release/obj.target/ghostscript4js/src/ghostscript4js.o
  SOLINK_MODULE(target) Release/obj.target/ghostscript4js.node
g++: error: /usr/lib/x86_64-linux-gnu/libgs.so: Aucun fichier ou dossier de ce type
make: *** [ghostscript4js.target.mk:139: Release/obj.target/ghostscript4js.node] Error 1
make : on quitte le répertoire « /home/michael/src/asciidoctor-pdf.js/node_modules/ghostscript4js/build »
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/home/michael/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:223:5)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:272:12)
gyp ERR! System Linux 5.0.0-38-generic
gyp ERR! command "/home/michael/.nvm/versions/node/v12.14.1/bin/node" "/home/michael/.nvm/versions/node/v12.14.1/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/michael/src/asciidoctor-pdf.js/node_modules/ghostscript4js
gyp ERR! node -v v12.14.1
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok 

> puppeteer@2.0.0 install /home/michael/src/asciidoctor-pdf.js/node_modules/puppeteer
> node install.js

Downloading Chromium r706915 - 118.3 Mb [====================] 100% 0.0s 
Chromium downloaded to /home/michael/src/asciidoctor-pdf.js/node_modules/puppeteer/.local-chromium/linux-706915

> core-js@2.6.11 postinstall /home/michael/src/asciidoctor-pdf.js/node_modules/core-js
> node -e "try{require('./postinstall')}catch(e){}"

Thank you for using core-js ( https://github.com/zloirock/core-js ) for polyfilling JavaScript standard library!

The project needs your help! Please consider supporting of core-js on Open Collective or Patreon: 
> https://opencollective.com/core-js 
> https://www.patreon.com/zloirock 

Also, the author of core-js ( https://github.com/zloirock ) is looking for a good job -)

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ghostscript4js@3.1.1 (node_modules/ghostscript4js):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: ghostscript4js@3.1.1 install: `node-gyp rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

added 490 packages from 805 contributors and audited 3156 packages in 192.303s
found 0 vulnerabilities
```

I am not sure if this error is important. Some clarifications would be welcomed.

**Comment by danyill** [comment]
@rohel01 you need the Ghostscript libraries, try `sudo apt install libgs-dev` before you install.

**Comment by Mogztter** [comment]
@rohel01 Could you please confirm that this issue is gone on master branch?

**Comment by Mogztter** [comment]
I'm closing, feel free to reopen if you still have this issue with the latest release.
